postgres:
  spec:
    replicas: 1
    containerPort: 5432

  auth:
    username: postgres
    password: postgres
    database: postgres

  image:
    name: "postgres"
    tag: "15"
    imagepullpolicy: "IfNotPresent"

  persistence:
    enabled: True
    className: linode-block-storage-retain
    accessMode: ReadWriteOnce
    capacity: 10Gi
    volume:
      name: postgresql
      path: "/var/lib/postgresql/data"
  service:
    type: ClusterIP
