postgres:
  spec:
    replicas: 1
    containerPort: 5432

  auth:
    username: postgres
    password: postgres
    database: social

  image:
    name: "postgres"
    tag: "15"
    imagepullpolicy: "IfNotPresent"

  persistence:
    enabled: True
    className: linode-block-storage-retain
    accessMode: ReadWriteOnce
    capacity: 8Gi
    volume:
      name: postgresql
      path: "/data/postgres"
  service:
    type: ClusterIP
