apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-agent
  namespace: prefect
  labels:
    app.kubernetes.io/name: prefect-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: agent
spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: prefect-agent
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prefect-agent
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: agent
    spec:
      securityContext: {{- .Values.agent.podSecurityContext | toYaml | nindent 8 }}
      containers:
        - name: prefect-agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.prefectTag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          # command: ["prefect", "agent", "start", "-q", '{{ join "," .Values.agent.config.workQueues }}']
          workingDir: /code
          env:
            - name: HOME
              value: /home/prefect
            - name: PREFECT_AGENT_PREFETCH_SECONDS
              value: {{ .Values.agent.config.prefetchSeconds | quote }}
            - name: PREFECT_AGENT_QUERY_INTERVAL
              value: {{ .Values.agent.config.queryInterval | quote }}
            - name: PREFECT_API_URL
              value: {{ .Values.agent.orionApiConfig.apiUrl | quote }}
            - name: PREFECT_DEBUG_MODE
              value: {{ .Values.agent.image.debug | quote }}
            - name: RIOT_API_URL
              value: {{ .Values.external.league.RIOT_API_URL | quote }}
            - name: RIOT_API_KEY
              value: {{ .Values.external.league.RIOT_API_KEY }}
          volumeMounts:
            - mountPath: /home/prefect
              name: scratch
              subPathExpr: home
            - mountPath: /tmp
              name: scratch
              subPathExpr: tmp
      volumes:
        - name: scratch
          emptyDir: {}
