apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prefect-orion
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: orion
type: Opaque
stringData:
  PREFECT_ORION_DATABASE_CONNECTION_URL: {{ .Values.postgresql.auth.url | quote }}
  DATABASE_DATABASE: {{ .Values.postgresql.auth.database | quote }}
  DATABASE_HOST:     {{ .Values.postgresql.auth.host     | quote }}
  DATABASE_USER:     {{ .Values.postgresql.auth.username | quote }}
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  DATABASE_ENGINE:   {{ .Values.postgresql.auth.engine   | quote }}
  DATABASE_PORT:     {{ .Values.postgresql.auth.port     | quote }}