apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prefect-orion
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: orion
data:
  PREFECT_ORION_DATABASE_CONNECTION_URL: {{ include "orion.postgres-connstr" . | b64enc | quote  }}