---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-pv-claim
  labels:
    app: {{ .Chart.Name }}
spec:
  storageClassName: {{ .Values.postgres.persistence.className }}
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.capacity }}