apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-config
  labels:
    app.kubernetes.io/component: apply-migrate-job
data:
{{- range $k, $v := .Values.env.normal }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
