apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name}}-apply-migrations
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    tag: "{{ .Values.image.tag }}"
spec:
  activeDeadlineSeconds: 600
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: {{.Release.Name}}-migrations-job
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["./manage.py","migrate"]
        env:
          - name: DEBUG
            value: "False"
          - name: DATABASE_URL
            value: {{ .Values.env.secret.DATABASE_URL }}
          - name: SECRET_KEY
            value: {{ .Values.env.secret.SECRET_KEY }}
        {{- range $k, $v := .Values.env.normal }}
          - name: {{ $k }}
            value: {{ $v | quote }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{.Release.Name}}-config
