apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
{{- range $k, $v := .Values.env.secret }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
  REDIS_URL: {{ include "redis.url" . | b64enc | quote }}
