apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ingressClassName: {{ .Values.apiIngress.ingressClassName | quote }}
  rules:
    - host: {{ .Values.apiIngress.hostname }}
      http:
        paths:
          - path: {{ .Values.apiIngress.path }}
            pathType: {{ .Values.apiIngress.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}-service
                port: 
                  name: minio-api
