apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  root-user: {{ .Values.auth.rootUser | quote }}
  root-password: {{ .Values.auth.rootPassword | quote }}