apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - name: minio-api
      port: {{ .Values.service.ports.api }}
      targetPort: minio-api
      nodePort: null
    - name: minio-console
      port: {{ .Values.service.ports.console }}
      targetPort: minio-console
      nodePort: null
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
